### PR TITLE
Publish benchmarks to GitHub Pages

### PR DESCRIPTION
**Pull request by lafrenierejm**
On each commit to `main`, run benchmarks and publish them to the `gh-pages` branch. That branch can be configured as the source of GitHub Pages, so it gets built and published on each change. See https://lafrenierejm.github.io/ripsecrets/dev/bench/ for an example of benchmarks published from my fork.

### CODE REVIEW

**Comment by lafrenierejm** [comment]
@sirwart Any interest in this PR? No worries if not, just hoping to get some closure either way.

**Comment by sirwart** [comment]
@lafrenierejm sorry, I didn't realize there were still open PRs. The change looks good, my only question is how does it know it's being pushed to the `gh-pages` branch? I didn't see anything about that branch in the configuration.

**Comment by lafrenierejm** [comment]
> sorry, I didn't realize there were still open PRs.

@sirwart No worries!

> The change looks good, my only question is how does it know it's being pushed to the gh-pages branch? I didn't see anything about that branch in the configuration.

The branch is configured upstream in the action itself: https://github.com/benchmark-action/github-action-benchmark/blob/v1.14.0/action.yml#L22

**Comment by sirwart** [comment]
Got it, thanks!

**Comment by lafrenierejm** [comment]
@sirwart Mind creating the `gh-pages` branch to fix <https://github.com/sirwart/ripsecrets/actions/runs/3570464167/jobs/6001461719>? That probably could have been done in the action itself (sorry), but at this point it might be worth just doing manually since it's a one-time thing.

**Comment by sirwart** [comment]
No problem, I just created it

**Pull request merged**
